# Generated by Django 2.2.4 on 2021-03-05 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=600)),
                ('completed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Admin_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to='main_app.User')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_tickets', to='main_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_messages', to='main_app.ChatRoom')),
                ('message_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_created', to='main_app.User')),
                ('ticket_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_messages', to='main_app.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='User1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chatrooms', to='main_app.User'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='User2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_chatrooms', to='main_app.User'),
        ),
    ]
